### ISSUE TITLE
ToJson() should return json in usable format

### ISSUE THREAD

**Issue by juralaakkonen** [CommunityHiQ/Frends.Community.ConvertExcelFile#7]
At the moment ToJson() returns unusable json -  it is just XML converted to JSON, which return this type of json:
```
{
	"@workbook_name": "excel_filename.xls",
	"worksheet": {
		"@worksheet_name": "Sheet1",
		"row": [
			{
				"@row_header": "1",
				"column": [
					{
						"@column_header": "A",
						"#text": "Firstname"
					},
					{
						"@column_header": "B",
						"#text": "Lastname"
					}
...
```
This is totally unusable. Same thing with ToXml() methods output.
These should be done from scratch so that ToJson() returns for example:
```
{
  "workbook name" : "file name.xsl",
  "worksheets":[
    {
      "name" : "Sheet1",
      "rows" : [
        "column": "value"
      ]
    }
  ]
}
```
Usually excel data imported is in some kinf of table format, so it would be nice to be able to give some parameters in Task (header row, etc) that would map the data to something like:
```
...
  "rows" : [
      "header row column value" : "current data row column value",
      ....
   ]
}
```

**Comment by Svenskapojkarna** [comment]
This issue has now been fixed in version 1.7.1.
