### ISSUE TITLE
Date times are conversion depends computer settings

### ISSUE THREAD

**Issue by OssiGalkin** [CommunityHiQ/Frends.Community.ConvertExcelFile#8]
At the moment settings of FRENDS agent computer affects how date times are converted.

For example same cell could be converted to:
<column column_header="D">12/29/2017 12:00:00 AM</column>
or
<column column_header="D">29.12.2017 0:00:00</column>

**Comment by RikuVirtanen** [comment]
Issue fixed by implementing selection for date formats and boolean value for ShortDatePattern if the time stamp is not needed. Default values for date format: Agent's computer's date format and for ShortDatePattern: false
